FROM node:22-alpine

# Set timezone
ENV TZ=Asia/Ho_Chi_Minh

# Set working directory
WORKDIR /app

# Install dependencies for development
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    && ln -sf python3 /usr/bin/python

# Copy package files
COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

# Install all dependencies (including devDependencies)
RUN npm install

# Copy source code
COPY . .

# Expose port (thay đổi port theo cấu hình của bạn)
EXPOSE 3000

# Start development server
CMD ["npm", "run", "start:dev"]
